

#define PIN_SDRAM_CAS 0
#define PIN_SDRAM_RAS 1
#define PIN_SDRAM_WE 2
#define PIN_SDRAM_CS 3
#define PIN_SDRAM_CKE 4
#define PIN_SDRAM_DQML 5
#define PIN_SDRAM_DQMH 6
#define PIN_SDRAM_ADDR0 7
#define PIN_SDRAM_ADDR1 8
#define PIN_SDRAM_ADDR2 9
#define PIN_SDRAM_ADDR3 10
#define PIN_SDRAM_ADDR4 11
#define PIN_SDRAM_ADDR5 12
#define PIN_SDRAM_ADDR6 13
#define PIN_SDRAM_ADDR7 14
#define PIN_SDRAM_ADDR8 15
#define PIN_SDRAM_ADDR9 16
#define PIN_SDRAM_ADDR10 17
#define PIN_SDRAM_ADDR11 18
#define PIN_SDRAM_ADDR12 19
#define PIN_SDRAM_BA0 20
#define PIN_SDRAM_BA1 21